export const copy = {
  brand: "Tetra Colors",
  eyebrow: "开源 · 自托管 · 多人在线",
  intro: "用颜色、数字与时机，和朋友完成一场轻快的牌局。",
  nicknameLabel: "你的昵称",
  nicknamePlaceholder: "例如：青鸟",
  nicknameRequired: "请先输入昵称，再加入房间。",
  roomCodeLabel: "房间码",
  roomCodePlaceholder: "5 位房间码",
  createRoom: "创建新房间",
  joinRoom: "加入房间",
  entering: "正在进入…",
  reconnecting: "正在重新连接房间…",
  connecting: "正在连接牌桌…",
  connection: {
    connected: "已连接",
    connecting: "连接中",
    reconnecting: "重连中",
    disconnected: "连接中断",
    idle: "未连接",
  },
  room: "房间",
  copyCode: "复制房间码",
  copied: "已复制",
  leave: "离开房间",
  leaveConfirmation: {
    "last-human": "你是房间里的最后一名真人玩家。离开后房间会立即销毁，确定离开吗？",
    "active-game": "对局仍在进行。离开后你的座位将由电脑接管，确定离开吗？",
  },
  lobbyTitle: "等待玩家",
  lobbyIntro: "邀请朋友输入房间码，房主准备好后即可开始。",
  host: "房主",
  you: "你",
  offline: "暂时离线",
  bot: "电脑玩家",
  addBot: "添加电脑玩家",
  removeBot: "移除",
  startGame: "开始对局",
  waitingForHost: "等待房主开始",
  needPlayers: "至少需要两位玩家",
  seats: "个席位",
  currentColor: "当前颜色",
  drawCard: "抽一张牌",
  drawing: "正在抽牌…",
  passTurn: "结束回合",
  passing: "正在结束…",
  yourTurn: "轮到你了",
  theirTurn: "正在行动",
  cards: "张牌",
  yourHand: "你的手牌",
  chooseColor: "选择接下来的颜色",
  chooseColorHint: "功能牌打出后，牌桌将切换到你选择的颜色。",
  close: "取消",
  reconnectOverlay: "连接正在恢复，操作会在重连后开放。",
  roundFinished: "本局结束",
  youWon: "你率先清空了手牌",
  playerWon: "率先清空了手牌",
  rematch: "再来一局",
  waitingRematch: "等待房主开启下一局",
  directionClockwise: "顺向",
  directionCounterClockwise: "逆向",
  skipped: "本回合被跳过",
  skipCleared: "已解除跳过状态",
  skippedStatus: "本回合不可行动",
  cardKinds: {
    skip: "跳过",
    reverse: "反向",
    "draw-two": "抽二",
    wild: "换色",
    "wild-draw-four": "换色抽四",
  },
  colors: {
    coral: "珊瑚",
    amber: "琥珀",
    teal: "青绿",
    azure: "天蓝",
  },
  unknownError: "发生了意外问题，请重试。",
  invalidSession: "房间会话已失效，请重新加入。",
  difficulty: {
    easy: "轻松",
    medium: "标准",
    hard: "敏锐",
  },
} as const;
