export const copy = {
  brand: "Tetra Colors",
  eyebrow: "开源 · 自托管 · 多人在线",
  intro: "用颜色、数字与时机，和朋友完成一场轻快的牌局。",
  nicknameLabel: "你的昵称",
  nicknamePlaceholder: "例如：青鸟",
  roomCodeLabel: "房间码",
  roomCodePlaceholder: "5 位房间码",
  createRoom: "创建新房间",
  joinRoom: "加入房间",
  entering: "正在进入…",
  reconnecting: "正在重新连接房间…",
  connecting: "正在连接牌桌…",
  connection: {
    connected: "已连接",
    connecting: "连接中",
    reconnecting: "重连中",
    disconnected: "连接中断",
    idle: "未连接",
  },
  room: "房间",
  copyCode: "复制房间码",
  copied: "已复制",
  leave: "离开房间",
  lobbyTitle: "等待玩家",
  lobbyIntro: "邀请朋友输入房间码，房主准备好后即可开始。",
  host: "房主",
  you: "你",
  offline: "暂时离线",
  bot: "电脑玩家",
  addBot: "添加电脑玩家",
  removeBot: "移除",
  startGame: "开始对局",
  waitingForHost: "等待房主开始",
  needPlayers: "至少需要两位玩家",
  seats: "个席位",
  tableLoading: "牌桌已开启",
  tableLoadingHint: "大厅流程验证完成，对局界面将在下一阶段接入。",
  unknownError: "发生了意外问题，请重试。",
  invalidSession: "房间会话已失效，请重新加入。",
  difficulty: {
    easy: "轻松",
    medium: "标准",
    hard: "敏锐",
  },
} as const;
